name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  DISPLAY: :1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.11.2

      - name: Init environment
        run: pip install -r requirements.txt -r requirements-dev.txt
        
      - name: Run tests
        run: pytest -vv --cov --cov-report=term-missing --cov-report=xml:coverage.xml --tb=short

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'